### ISSUE TITLE
[Bug?!]: Admin.cs的异步方法以同步方式运行

### ISSUE THREAD

**Issue by Emerald-AM9** [Abjust/2kbit-csnew#1]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 如果您正在使用修改过的2kbit发行版：我确定这个Bug是2kbit本身就存在的，而非此发行版引入的问题。
- [X] 我已经仔细阅读上述教程和 ["《提问的智慧》"](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)。
- [X] 我十分肯定，绝对不是因为我自己的问题导致的。
- [X] 我确定这是个有意义的Issue，且目前没有解决方案。

### 使用的2kbit发行版

2kbit-csnew 1.0.0

### 重现步骤

1.使用终端程序打开项目文件夹（Net_Codeintp_cs）
2.以命令行方式运行2kbit-csnew（dotnet run）

### 期望的结果是什么？

不出现警告，直接运行程序

### 实际的结果是什么？

出现警告：
(dir)/Net_Codeintp_cs/Modules/Group/Admin.cs(12,27): warning CS1998: 此异步方法缺少 "await" 运算符，将以同步方式运行。请考虑使用 "await" 运算符等待非阻止的 API 调用，或者使用 "await Task.Run(...)" 在后台线程上执行占用大量 CPU 的工作。 [(dir)/Net_Codeintp_cs/Net_Codeintp_cs.csproj]

**Comment by Abjust** [comment]
你使用的是1.0.0版本，Admin.cs的功能是在b_23w01a得以实现的，因此你的版本的Admin.cs相当于无用
